POST http://localhost:3000/api/apply
content-type: application/json

{
    "applicant": "Faizur",
    "email": "faizur634324@w.com",
    "mobile":"8251610901",
    "fatherName":"XYZ",
    "address":"madhopur chansadjhsadbjashd sdfkjbdsakf",
    "rtiQuery":"Next.js API Routes Validation using YUP: Share frontend and backend validation using YUP schemas",
    "organizationAddress":"organizationAddress organizationAddress organizationAddress ",
    "orgState":"orgState"
}

###
GET http://localhost:3000/api/login

###
GET http://localhost:3000/api/user
content-type: application/json
Authorization: "hello"

###

GET http://localhost:3000/api/article-detail
Authorization: "hello"